[program:queue-critical]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan queue:work redis --queue=%(ENV_QUEUE_TIER_CRITICAL)s --sleep=%(ENV_QUEUE_WORKER_SLEEP)s --tries=3 --timeout=%(ENV_QUEUE_WORKER_TIMEOUT)s --backoff=60,300,900 --max-time=%(ENV_QUEUE_WORKER_MAX_TIME)s --no-interaction
directory=/var/www/backend
autostart=true
autorestart=true
startretries=3
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
user=www-data
numprocs=%(ENV_QUEUE_WORKER_CRITICAL_PROCS)s
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan queue:work redis --queue=%(ENV_QUEUE_TIER_DEFAULT)s --sleep=%(ENV_QUEUE_WORKER_SLEEP)s --tries=3 --timeout=%(ENV_QUEUE_WORKER_TIMEOUT)s --backoff=60,180 --max-time=%(ENV_QUEUE_WORKER_MAX_TIME)s --no-interaction
directory=/var/www/backend
autostart=true
autorestart=true
startretries=3
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
user=www-data
numprocs=%(ENV_QUEUE_WORKER_DEFAULT_PROCS)s
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:queue-low]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan queue:work redis --queue=%(ENV_QUEUE_TIER_LOW)s --sleep=%(ENV_QUEUE_WORKER_SLEEP)s --tries=2 --timeout=%(ENV_QUEUE_WORKER_TIMEOUT)s --backoff=120 --max-time=%(ENV_QUEUE_WORKER_MAX_TIME)s --no-interaction
directory=/var/www/backend
autostart=true
autorestart=true
startretries=3
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
user=www-data
numprocs=%(ENV_QUEUE_WORKER_LOW_PROCS)s
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
