<?php

use App\Http\Controllers\Api\V1\Admin\ClientController;
use App\Http\Controllers\Api\V1\Admin\InvoiceController;
use App\Http\Controllers\Api\V1\Admin\InvoiceGatewayController;
use App\Http\Controllers\Api\V1\Admin\InvoicePaymentController;
use App\Http\Controllers\Api\V1\Admin\OrderCheckoutController;
use App\Http\Controllers\Api\V1\Admin\OrderController;
use App\Http\Controllers\Api\V1\Admin\PaymentController;
use App\Http\Controllers\Api\V1\Admin\ProductController;
use App\Http\Controllers\Api\V1\Admin\ProductGroupController;
use App\Http\Controllers\Api\V1\Admin\ProductPricingController;
use App\Http\Controllers\Api\V1\Admin\ProvisioningJobController;
use App\Http\Controllers\Api\V1\Admin\ServerController;
use App\Http\Controllers\Api\V1\Admin\ServerGroupController;
use App\Http\Controllers\Api\V1\Admin\ServerPackageController;
use App\Http\Controllers\Api\V1\Admin\ServiceController;
use App\Http\Controllers\Api\V1\Admin\ServiceProvisioningController;
use Illuminate\Support\Facades\Route;

Route::apiResource('clients', ClientController::class);
Route::get('invoices/{invoice}/gateway-options', [InvoiceGatewayController::class, 'index'])->name('invoices.gateway-options.index');
Route::post('invoices/{invoice}/gateway-checkouts', [InvoiceGatewayController::class, 'store'])->name('invoices.gateway-checkouts.store');
Route::post('invoices/{invoice}/gateway-checkouts/paypal/capture', [InvoiceGatewayController::class, 'capturePayPal'])->name('invoices.gateway-checkouts.paypal.capture');
Route::post('invoices/{invoice}/payments', [InvoicePaymentController::class, 'store'])->name('invoices.payments.store');
Route::apiResource('invoices', InvoiceController::class);
Route::post('orders/review', [OrderCheckoutController::class, 'review'])->name('orders.review');
Route::post('orders/place', [OrderCheckoutController::class, 'place'])->name('orders.place');
Route::post('orders/{order}/place', [OrderController::class, 'place'])->name('orders.place-existing');
Route::apiResource('orders', OrderController::class);
Route::get('payments', [PaymentController::class, 'index'])->name('payments.index');
Route::apiResource('provisioning-jobs', ProvisioningJobController::class)->only(['index', 'show']);
Route::apiResource('product-groups', ProductGroupController::class);
Route::apiResource('products', ProductController::class);
Route::get('products/{product}/pricing', [ProductPricingController::class, 'show'])->name('products.pricing.show');
Route::put('products/{product}/pricing', [ProductPricingController::class, 'update'])->name('products.pricing.update');
Route::apiResource('server-groups', ServerGroupController::class);
Route::put('servers/{server}/packages', [ServerPackageController::class, 'update'])->name('servers.packages.update');
Route::apiResource('servers', ServerController::class);
Route::post('services/{service}/operations/{operation}', [ServiceProvisioningController::class, 'store'])->name('services.operations.store');
Route::apiResource('services', ServiceController::class);
